language: java
jdk:
  - openjdk8
# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false
# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
before_script:
  - git clone https://github.com/phac-nml/irida.git
  - cd irida && git fetch --all --tags && git checkout 19.09
  - cd lib && ./install-libs.sh && cd ..
  - mvn clean install -DskipTests && cd ..
script:
  # - cd sanbi-bvc-pipeline-plugin
  # - mvn clean package && cd ..
  # - cd tb-sample-report-pipeline-plugin
  # - mvn clean package && cd ..
  - cd tb-sample-report-pipeline-plugin
  - mvn clean package
